.TH AirInv 3 "C++ Airline Inventory Manager Library" "AirInv Team" \" -*- nroff -*-
.SH NAME
airinv - C++ Airline Inventory Manager Library
.SH SYNOPSIS
#include <airinv/...>
.SH DESCRIPTION
That project aims at providing a clean API, and the corresponding C++
implementation, for processing airline inventories. That library uses
the Standard Airline IT C++ object model
(http://sf.net/projects/stdair), which gathers a collection of
routines for travel market simulation. The routines are written from
scratch by the Airinv team in C++, and present a modern Applications
Programming Interface (API) for C/C++ programmers, allowing wrappers
to be written for very high level languages.
.PP
The library covers the following areas,
.TP
.nf
.BR
Architecture
.fi
.PP
Please report any bugs to 
.B https://sourceforge.net/apps/trac/airinv/report
